name: Package and Publish Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: echo "Skipping tests..."

      - name: Setup Node.js 14 for vsce
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Package Extension
        run: npx vsce package

      - name: Publish Extension
        run: npx vsce publish -p ${{ secrets.VSCE_ACCESSTOKEN }}
